[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "gcc", "nodejs", "git", "make"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "make install_frontend"
]

[phases.build]
cmds = [
  "make build_frontend",
  "make build"
]

[start]
cmd = "make run"
