[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "gcc", "nodejs", "git"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "cd src/frontend && npm install"
]

[phases.build]
cmds = [
  "cd src/frontend && npm run build",
  "python setup.py build"
]

[start]
cmd = "python -m langflow"
